spring:
  application:
    name: product-server   # Tên service phải giống tên folder hoặc tên file config
  datasource:
    url: jdbc:mysql://prod-db-server:3306/haiphuoc_database
    username: khangdb  
    password: Tranquockhang123

eureka:
  client:
    service-url:
      defaultZone: http://eureka-prod-server:8761/eureka

server:
  port: 8081
