spring:
  application:
    name: product-server  # BẮT BUỘC PHẢI CÓ
  datasource:
    url: jdbc:mysql://localhost:3306/haiphuoc_database
    username: khangdb  
    password: Tranquockhang123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081
