server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-prod-server:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/product
    username: prod_user
    password: prod_password
